#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Issue #219: Sage's name for a Built App and the Domino App's name can
# diverge for ever. Before Sage can carry a rename to the deployment we have
# to know whether the apps API will take one. This probe answers that
# against the live control plane, and writes the answer down so nobody has
# to run it twice.
#
# Already settled before this script existed, so do not re-probe it:
#   - the API answers this laptop (GET /v4/users/self and the beta app list
#     both 200 with backend/.env's GATEWAY_API_KEY). No Builder needed.
#   - PATCH /api/apps/beta/apps/{id} IS routed: on a nil ObjectId it answers
#     400 "Cannot find app with nil bson id", i.e. the handler ran.
#     PUT, POST and OPTIONS on that path all 404 "endpoint not found".
#
# What is left needs one real, disposable App, which is what this walks you
# through.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1   # findings + backend/.env are repo-relative

TOTAL_STAGES=6

STATE_DIR="${TMPDIR:-/tmp}/sage-rename-probe"
mkdir -p "$STATE_DIR"
ENV_FILE="$STATE_DIR/state.env"     # resume file for ask/write_env. No project .env is touched.
BEFORE="$STATE_DIR/app-before.json"
AFTER="$STATE_DIR/app-after.json"
RESP="$STATE_DIR/resp.json"
FINDINGS="docs/live-runs/$(date +%F)-app-rename-probe.md"

# api METHOD PATH [JSON_BODY] -> prints the response body, sets $API_STATUS.
api() {
  local m="$1" p="$2" b="${3:-}"
  if [[ -n "$b" ]]; then
    API_STATUS=$(curl -sS -o "$RESP" -w '%{http_code}' -X "$m" \
      -H "Authorization: Bearer $TOKEN" -H "Accept: application/json" \
      -H "Content-Type: application/json" -d "$b" "$HOST$p") || API_STATUS=000
  else
    API_STATUS=$(curl -sS -o "$RESP" -w '%{http_code}' -X "$m" \
      -H "Authorization: Bearer $TOKEN" -H "Accept: application/json" "$HOST$p") || API_STATUS=000
  fi
  cat "$RESP"
}

# urlenc STRING -> the same string, safe in a URL path segment.
urlenc() { python3 -c 'import sys,urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "$1"; }

# field a.b.c < json -> the value, or "" when absent.
field() {
  python3 -c '
import sys, json
try: d = json.load(sys.stdin)
except Exception: print(""); sys.exit()
for k in sys.argv[1].split("."):
    d = d.get(k) if isinstance(d, dict) else None
print("" if d is None else d)' "$1"
}

# env_from_dotenv KEY -> the value in backend/.env, or "".
env_from_dotenv() {
  [[ -f backend/.env ]] || return 0
  grep -E "^${1}=" backend/.env | tail -n1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' || true
}

# ──────────────────────────────────────────────────────────────────────────
banner "Sage #219 · does a rename reach the deployed App?"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Credential and reach"
say "This talks to Domino's public API straight from your laptop."
note "backend/.env's GATEWAY_API_KEY is a JWT the REST API takes as a Bearer token."
printf '\n'

HOST_DEFAULT=$(env_from_dotenv DOMINO_API_HOST)
[[ -z "$HOST_DEFAULT" ]] && HOST_DEFAULT="https://cloud-dogfood.domino.tech"
if [[ "$HOST_DEFAULT" == *nucleus-frontend* ]]; then
  warn "backend/.env holds the INTERNAL host. That one is not reachable from here."
  HOST_DEFAULT="https://cloud-dogfood.domino.tech"
fi
say "Host: $HOST_DEFAULT"
# y/N gates default to No, so ask the question whose No keeps the default.
if confirm "Probe a DIFFERENT host?"; then
  ask PROBE_HOST "Paste the public Domino host (https://...):"
  HOST="$PROBE_HOST"
else
  HOST="$HOST_DEFAULT"
fi
HOST="${HOST%/}"
write_env PROBE_HOST "$HOST"

TOKEN=$(env_from_dotenv GATEWAY_API_KEY)
if [[ -z "$TOKEN" ]]; then
  warn "no GATEWAY_API_KEY in backend/.env."
  ask_secret PROBE_TOKEN "Paste a Domino Bearer token:"
  TOKEN="$PROBE_TOKEN"
else
  note "token read from backend/.env (never printed, never written anywhere)"
fi

printf '\n'
python3 -c '
import sys, base64, json, datetime
t = sys.argv[1]; p = t.split(".")
if len(p) != 3:
    print("  token is not a JWT, so its life cannot be read here."); sys.exit()
b = p[1] + "=" * (-len(p[1]) % 4)
exp = json.loads(base64.urlsafe_b64decode(b)).get("exp")
if not exp: print("  JWT carries no exp."); sys.exit()
when = datetime.datetime.utcfromtimestamp(exp)
left = when - datetime.datetime.utcnow()
print(f"  token expires {when.isoformat()}Z ({left.days} days left)" if left.days >= 0
      else f"  TOKEN EXPIRED {when.isoformat()}Z -- get a fresh one before going on.")' "$TOKEN"

api GET /v4/users/self > "$RESP.self"
if [[ "$API_STATUS" != "200" ]]; then
  warn "GET /v4/users/self answered $API_STATUS. The API is not reachable with this token."
  note "Fall back: run this inside a Domino Builder terminal, where DOMINO_API_HOST"
  note "and the token sidecar at localhost:8899 both exist."
  exit 1
fi
OWNER=$(field userName < "$RESP.self")
printf '  %s✓%s reachable as %s\n' "$GREEN" "$RESET" "$OWNER"
write_env PROBE_OWNER "$OWNER"
pause "Press Enter for stage 2."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Pick the throwaway App"
say "The probe renames a real Domino App, so it must be one you do not mind breaking."
say "Publish a fresh one through Sage. That is also the only target that proves the"
say "Launchpad card follows for a Sage-published App, which is what #219 is about."
printf '\n'
note "Wherever you click Publish. Two forms, both fine:"
note "  your workspace — the Workbench runs as a pluggable workspace tool, so the"
note "  session URL ($HOST/<owner>/<project>/notebookSession/<id>/) IS the Workbench"
note "  or the published Workbench App: $HOST/modelproducts/<app id>?scope=project"
ask SAGE_HUB_URL "Paste the Workbench URL:"
write_env SAGE_HUB_URL "$SAGE_HUB_URL"
open_url "$SAGE_HUB_URL"
step "In Sage, build or open any Project, then Publish."
step "Name the App exactly:  Sage rename probe A"
step "Wait for the publish to finish (the App has to exist, running or not)."
pause "Published? Press Enter to list your Apps."

printf '\n'
PROBE_TOKEN_FOR_LIST="$TOKEN" python3 - "$HOST" "$OWNER" "$STATE_DIR/mine.tsv" <<'PY'
import os, sys, json, urllib.request
host, owner, out = sys.argv[1], sys.argv[2], sys.argv[3]
tok = os.environ["PROBE_TOKEN_FOR_LIST"]
def get(p):
    r = urllib.request.Request(host + p, headers={"Authorization": "Bearer " + tok,
                                                  "Accept": "application/json"})
    return json.load(urllib.request.urlopen(r))
off, total, rows = 0, None, []
# The beta list is GLOBAL -- every App on the deployment -- so page it and match
# on the nested owner client-side. ?projectId= is honoured but we have no project id yet.
while total is None or off < total:
    d = get(f"/api/apps/beta/apps?limit=100&offset={off}")
    items = d.get("items") or []
    total = (d.get("metadata") or {}).get("totalCount") or 0
    for a in items:
        pr = a.get("project") or {}
        if pr.get("ownerUsername") == owner or (a.get("publisher") or {}).get("name") == owner:
            st = ((a.get("currentVersion") or {}).get("currentInstance") or {}).get("status") or "-"
            rows.append((a["id"], a.get("name") or "", pr.get("name") or "", st))
    if not items:
        break
    off += len(items)
with open(out, "w") as f:
    for i, r in enumerate(rows, 1):
        f.write("\t".join([str(i), *r]) + "\n")
        print(f"  {i:>2}. {r[1][:38]:<38}  {r[3]:<9} {r[2][:22]:<22} {r[0]}")
if not rows:
    print("  no Apps found for", owner)
PY

ask APP_INDEX "Which number is the throwaway?"
APP_ID=$(awk -F'\t' -v i="$APP_INDEX" '$1==i{print $2}' "$STATE_DIR/mine.tsv")
if [[ -z "$APP_ID" ]]; then warn "no App at $APP_INDEX."; exit 1; fi
# The Workbench App is in that list too, and renaming the door is not the experiment.
if [[ "$SAGE_HUB_URL" == *"$APP_ID"* ]]; then
  warn "that is the Workbench App itself — the one you just published through."
  say "Pick the throwaway instead."
  exit 1
fi
write_env APP_ID "$APP_ID"

printf '\n'
awk -F'\t' -v i="$APP_INDEX" '$1==i{printf "  %s   (%s, project %s)\n", $3, $5, $4}' "$STATE_DIR/mine.tsv"
if ! confirm "Rename THAT App?"; then say "Nothing sent."; exit 0; fi

api GET "/api/apps/beta/apps/$APP_ID" > "$BEFORE"
if [[ "$API_STATUS" != "200" ]]; then warn "GET on the App answered $API_STATUS."; exit 1; fi
NAME_BEFORE=$(field name < "$BEFORE")
URL_BEFORE=$(field url < "$BEFORE")
ENTRY_BEFORE=$(field entryPoint < "$BEFORE")
VIS_BEFORE=$(field visibility < "$BEFORE")
VER_BEFORE=$(field currentVersion.id < "$BEFORE")
PROJ_BEFORE=$(field project.name < "$BEFORE")
for kv in "NAME_BEFORE=$NAME_BEFORE" "URL_BEFORE=$URL_BEFORE" "ENTRY_BEFORE=$ENTRY_BEFORE" \
          "VIS_BEFORE=$VIS_BEFORE" "VER_BEFORE=$VER_BEFORE" "PROJ_BEFORE=$PROJ_BEFORE"; do
  write_env "${kv%%=*}" "${kv#*=}"
done
printf '\n'
say "Snapshot saved to $BEFORE — this is what stage 4 diffs against."
note "name=$NAME_BEFORE | entryPoint=$ENTRY_BEFORE | visibility=$VIS_BEFORE"
note "url=$URL_BEFORE"
pause "Press Enter for stage 3."

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "The PATCH"
say "First the smallest body: {\"name\": ...} and nothing else."
printf '\n'
ask NEW_NAME "New name to try:"
if [[ -z "$NEW_NAME" ]]; then NEW_NAME="Sage rename probe B"; fi
write_env NEW_NAME "$NEW_NAME"
printf '\n'
warn "This changes a real App on $HOST. Stage 6 offers to put the name back."
if ! confirm "PATCH \"$NAME_BEFORE\" -> \"$NEW_NAME\" now?"; then
  say "Nothing sent. Re-run when you have a target you are happy to rename."
  exit 0
fi

MIN_BODY=$(python3 -c 'import json,sys; print(json.dumps({"name": sys.argv[1]}))' "$NEW_NAME")
api PATCH "/api/apps/beta/apps/$APP_ID" "$MIN_BODY" >/dev/null
PATCH_MIN_STATUS="$API_STATUS"
PATCH_MIN=$(head -c 400 "$RESP")
printf '\n  %sminimal body%s -> %s\n' "$BOLD" "$RESET" "$PATCH_MIN_STATUS"
note "${PATCH_MIN:-<empty body>}"
write_env PATCH_MIN_STATUS "$PATCH_MIN_STATUS"

PATCH_FULL_STATUS="not tried"
if [[ ! "$PATCH_MIN_STATUS" =~ ^2 ]]; then
  printf '\n'
  say "Refused. Some routes want the whole App body back, so try that next."
  if confirm "Re-send the whole App body with only the name changed?"; then
    FULL_BODY=$(python3 -c '
import json, sys
d = json.load(open(sys.argv[1]))
d["name"] = sys.argv[2]
for k in ("currentVersion", "publisher", "project"):   # server-owned, never sent back
    d.pop(k, None)
print(json.dumps(d))' "$BEFORE" "$NEW_NAME")
    api PATCH "/api/apps/beta/apps/$APP_ID" "$FULL_BODY" >/dev/null
    PATCH_FULL_STATUS="$API_STATUS"
    PATCH_FULL=$(head -c 400 "$RESP")
    printf '\n  %sfull body%s -> %s\n' "$BOLD" "$RESET" "$PATCH_FULL_STATUS"
    note "${PATCH_FULL:-<empty body>}"
  fi
fi
write_env PATCH_FULL_STATUS "$PATCH_FULL_STATUS"
pause "Press Enter for stage 4."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Read back, and diff every field"
say "The name is not the only thing that can move. A partial PATCH that replaces"
say "instead of merging would blank entryPoint or visibility, which is worse than"
say "no rename at all. So compare the whole App, not just the name."
printf '\n'
api GET "/api/apps/beta/apps/$APP_ID" > "$AFTER"
NAME_AFTER=$(field name < "$AFTER")
URL_AFTER=$(field url < "$AFTER")
python3 - "$BEFORE" "$AFTER" "$STATE_DIR/diff.txt" <<'PY'
import json, sys
b = json.load(open(sys.argv[1])); a = json.load(open(sys.argv[2])); lines = []
for k in sorted(set(b) | set(a)):
    if k in ("currentVersion",):        # a version's own fields move on their own
        continue
    ov, nv = b.get(k), a.get(k)
    if isinstance(ov, (dict, list)) or isinstance(nv, (dict, list)):
        ov, nv = json.dumps(ov, sort_keys=True), json.dumps(nv, sort_keys=True)
    if ov != nv:
        lines.append(f"{k}: {ov!r} -> {nv!r}")
lost = [k for k in b if b.get(k) not in (None, "", [], {}) and a.get(k) in (None, "", [], {})]
open(sys.argv[3], "w").write("\n".join(lines) + ("\nLOST: " + ", ".join(lost) if lost else ""))
if not lines:
    print("  nothing changed at all.")
for l in lines:
    print("  " + l)
if lost:
    print("\n  *** FIELDS LOST: " + ", ".join(lost) + " ***")
    print("  A rename built on this PATCH must send them back, or it is destructive.")
PY
printf '\n'
if [[ "$NAME_AFTER" == "$NEW_NAME" ]]; then
  printf '  %s✓ the API renamed it%s\n' "$GREEN" "$RESET"
else
  printf '  %s✗ the name did not change (still %s)%s\n' "$RED" "$NAME_AFTER" "$RESET"
fi
if [[ "$URL_AFTER" == "$URL_BEFORE" ]]; then
  printf '  %s✓ the URL did not move%s\n' "$GREEN" "$RESET"
else
  warn "the URL MOVED: $URL_BEFORE -> $URL_AFTER"
  note "A rename that moves the URL breaks the one promise publishing makes."
fi
write_env NAME_AFTER "$NAME_AFTER"
write_env URL_AFTER "$URL_AFTER"
pause "Press Enter for stage 5."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Your eyes: does the UI follow?"
say "The API's answer is not the UI's answer. Only you can read these three pages."
note "Say n if a page still shows the old name \"$NAME_BEFORE\"."
printf '\n'

step "1 of 3 — the App's own page (the Launchpad card)"
open_url "$HOST/modelproducts/$APP_ID?scope=project"
confirm "Does that page say \"$NEW_NAME\"?" && UI_CARD=yes || UI_CARD=no

PROJ_ENC=$(urlenc "$PROJ_BEFORE")
step "2 of 3 — the App list for the Project"
note "if this 404s, reach the list through the Project's Apps tab instead"
open_url "$HOST/u/$OWNER/$PROJ_ENC/apps"
confirm "Does the list say \"$NEW_NAME\"?" && UI_LIST=yes || UI_LIST=no

step "3 of 3 — the manage page Sage's Publish screen links to"
open_url "$HOST/u/$OWNER/$PROJ_ENC/apps/$APP_ID/$VER_BEFORE/details/overview"
confirm "Does the manage page say \"$NEW_NAME\"?" && UI_MANAGE=yes || UI_MANAGE=no

if [[ "$UI_CARD$UI_LIST$UI_MANAGE" == *no* ]]; then
  printf '\n'
  say "Something lagged. A republish is the usual suspect."
  note "A version POST needs an environmentId and a hardwareTierId, which this script"
  note "has no honest source for, and it spends hardware. So you drive this one."
  if confirm "Republish through Sage, then look again?"; then
    open_url "$SAGE_HUB_URL"
    step "Publish the same Project again. Do not change the name."
    pause "Republished and the pages reloaded? Press Enter."
    confirm "Do all three say \"$NEW_NAME\" NOW?" && UI_AFTER_REPUBLISH=yes || UI_AFTER_REPUBLISH=no
  fi
fi
UI_AFTER_REPUBLISH="${UI_AFTER_REPUBLISH:-not tried}"
pause "Press Enter to write the findings."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Write it down, then put the name back"
mkdir -p docs/live-runs
cat > "$FINDINGS" <<MD
# $(date +%F) · Can a rename reach the deployed App? (#219)

Run from a laptop against \`$HOST\`, as \`$OWNER\`, with \`backend/.env\`'s
\`GATEWAY_API_KEY\` as a Bearer token.

## Settled before the run, without touching anything

- The beta apps API **answers a laptop**. \`GET /v4/users/self\` and
  \`GET /api/apps/beta/apps\` both 200. #219 assumed a Builder was needed; that is
  only true of Sage's own publish path, which takes the sidecar token
  unconditionally (\`_build_control_plane\`).
- **\`PATCH /api/apps/beta/apps/{id}\` is routed.** On a nil ObjectId it answers
  400 \`Cannot find app with nil bson id\` — the handler ran. \`PUT\`, \`POST\` and
  \`OPTIONS\` on the same path all 404 \`Public api endpoint … not found\`.
- The body schema could **not** be read off the errors: the route resolves the
  App before it validates the body, so every bad body gives the same id error.

## The App

| | |
|---|---|
| id | \`$APP_ID\` |
| project | $PROJ_BEFORE |
| name before | $NAME_BEFORE |
| entryPoint before | \`$ENTRY_BEFORE\` |
| visibility before | $VIS_BEFORE |
| url before | \`$URL_BEFORE\` |

## What the API did

| | |
|---|---|
| PATCH, minimal body \`{"name": …}\` | **$PATCH_MIN_STATUS** |
| PATCH, whole body, name changed | **$PATCH_FULL_STATUS** |
| name after | $NAME_AFTER |
| url after | \`$URL_AFTER\` |
| url moved? | $([[ "$URL_AFTER" == "$URL_BEFORE" ]] && echo "no" || echo "**YES — see below**") |

Full-App diff, before against after:

\`\`\`
$(cat "$STATE_DIR/diff.txt")
\`\`\`

## What the UI did

| page | says the new name? |
|---|---|
| the App's own page / Launchpad card | $UI_CARD |
| the Project's App list | $UI_LIST |
| the manage page Publish links to | $UI_MANAGE |
| all three, after a republish | $UI_AFTER_REPUBLISH |

## Not run

- Nothing was checked for a **classic** (UI-created) App. Those live in another
  id space and are not in the beta list, so this says nothing about them.
- Only one App was renamed, once. Renaming twice, or renaming while a publish is
  in flight, was not tried.
MD
printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$FINDINGS"
printf '\n'

if [[ "$NAME_AFTER" == "$NEW_NAME" ]]; then
  if confirm "Put the name back to \"$NAME_BEFORE\"?"; then
    api PATCH "/api/apps/beta/apps/$APP_ID" \
      "$(python3 -c 'import json,sys; print(json.dumps({"name": sys.argv[1]}))' "$NAME_BEFORE")" >/dev/null
    note "restore -> $API_STATUS"
  fi
fi
if grep -q "^LOST:" "$STATE_DIR/diff.txt" 2>/dev/null; then
  printf '\n'
  warn "the PATCH lost fields. $BEFORE holds what they were."
fi

printf '\n'
say "Next: read $FINDINGS, then take it back to #219."
note "rename works  -> ADR + both writers carry the name to the deployment"
note "rename cannot -> ADR, and Sage stops implying it does"
finish
